### Q_NO_1

In [1]:
#  1. Import the numpy package under the name `np`
import numpy as np

### Q_NO_2

In [11]:
# 2. Print the numpy version and the configuration 
n= np.__version__
n

'1.24.2'

### Q_NO_3


In [10]:
#  Create a null vector of size 10 
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Q_NO_4

In [13]:
#### 4. How to find the memory size of any array 
b = np.size(a)
b

10

### Q_No_5

In [17]:
# How to get the documentation of the numpy add function from the command line?
# n = np.info(np.add)
b = np.info(np.mask_indices)

 mask_indices(n, mask_func, k=0)

Return the indices to access (n, n) arrays, given a masking function.

Assume `mask_func` is a function that, for a square array a of size
``(n, n)`` with a possible offset argument `k`, when called as
``mask_func(a, k)`` returns a new array with zeros in certain locations
(functions like `triu` or `tril` do precisely this). Then this function
returns the indices where the non-zero values would be located.

Parameters
----------
n : int
    The returned indices will be valid to access arrays of shape (n, n).
mask_func : callable
    A function whose call signature is similar to that of `triu`, `tril`.
    That is, ``mask_func(x, k)`` returns a boolean array, shaped like `x`.
    `k` is an optional argument to the function.
k : scalar
    An optional argument which is passed through to `mask_func`. Functions
    like `triu`, `tril` take a second argument that is interpreted as an
    offset.

Returns
-------
indices : tuple of arrays.
    The `n` arrays

### Q_NO_6

In [23]:
# Create a null vector of size 10 but the fifth value which is 1

n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Q_NO_7

In [28]:
# Create a vector with values ranging from 10 to 49 
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### Q_NO_8

In [30]:
# Reverse a vector (first element becomes last) 

a = [1,2,3,4,5]
b = a[::-1]
b

[5, 4, 3, 2, 1]

### Q_NO_9

In [41]:
# Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Q_NO_10

In [44]:
# Find indices of non-zero elements from [1,2,0,0,4,0] 
b = np.nonzero([1,2,0,0,4,0])
b

(array([0, 1, 4]),)

### Q_NO_11

In [47]:
# Create a 3x3 identity matrix
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Q_No_12

In [49]:
# Create a 3x3x3 array with random values
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [51]:
a = np.random.random((3,3,3))
a

array([[[0.60013104, 0.13564726, 0.57321107],
        [0.46666101, 0.39277599, 0.14370249],
        [0.31318205, 0.58532188, 0.88459681]],

       [[0.03256088, 0.01412392, 0.07545676],
        [0.30171626, 0.18695384, 0.39698416],
        [0.06747502, 0.02971103, 0.364265  ]],

       [[0.11380497, 0.37591516, 0.40445388],
        [0.84623009, 0.77204324, 0.83626287],
        [0.39863065, 0.86039764, 0.32335401]]])

### Q_No_13

In [57]:
# Create a 10x10 array with random values and find the minimum and maximum values
a = np.arange(100).reshape(10,10)
print(a)
b = a.min()
print("minimum",b)
c = a.max()
print("Maximum",c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
minimum 0
Maximum 99


In [60]:
z = np.random.random((10,10))
print(z)
print(z.min())
print(z.max())

[[0.33180248 0.42228718 0.43562487 0.27067297 0.25840703 0.76246139
  0.15312199 0.71844301 0.31830824 0.56853651]
 [0.64474215 0.960276   0.20369547 0.48983321 0.18064266 0.03993211
  0.02700445 0.56855709 0.41048527 0.17601755]
 [0.65832963 0.09041953 0.4735784  0.78161683 0.95493717 0.42572926
  0.62116379 0.6397573  0.11013011 0.38738317]
 [0.06423404 0.29023102 0.90937143 0.45478769 0.23333954 0.07370743
  0.61417607 0.69182122 0.44324667 0.41886588]
 [0.6657702  0.57868189 0.71586958 0.52894984 0.66808429 0.13055683
  0.22133503 0.96151168 0.00627081 0.29407177]
 [0.11121104 0.35853209 0.38930539 0.76797558 0.13375293 0.91822344
  0.35825116 0.07423308 0.11544077 0.75394368]
 [0.53539065 0.10759528 0.82005282 0.61686554 0.06796471 0.23747268
  0.05460034 0.24851395 0.43315145 0.22778681]
 [0.25266145 0.45418469 0.8624882  0.06935503 0.88596974 0.55038074
  0.11947197 0.3017704  0.37296971 0.01778106]
 [0.23666208 0.65127267 0.50273351 0.08298378 0.96764451 0.97102146
  0.68773998

### Q_NO_14

In [66]:
# Create a random vector of size 30 and find the mean value
a = np.random.random((30))
print(a)
print("Mean value is", a.mean())

[0.8327924  0.79930656 0.34961616 0.97863404 0.75145184 0.53629101
 0.92224766 0.42209478 0.13146999 0.84847977 0.03879689 0.60687531
 0.74093362 0.66864281 0.30767847 0.51349414 0.31799768 0.73366236
 0.07849019 0.01996098 0.42475045 0.62119829 0.3716035  0.42599674
 0.7359789  0.65674015 0.44392602 0.1709232  0.39424164 0.98581797]
Mean value is 0.527669783364082


### Q_NO_15

In [80]:
# Create a 2d array with 1 on the border and 0 inside 
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Q_No_16

In [86]:
#  How to add a border (filled with 0's) around an existing array? 
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### Q_NO_17

In [89]:
#  What is the result of the following expression? 
# python
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Q_NO_18

In [92]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
a = np.diag(1+np.arange(4),k = -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### Q_NO_19

In [96]:
#  Create a 8x8 matrix and fill it with a checkerboard pattern
z = np.zeros((8,8), dtype= int)
z[1::2,::2]= 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Q_NO_20

In [97]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
a = (np.unravel_index(99,(6,7,8)))
a

(1, 5, 3)

### Q_NO_21

In [106]:
# Create a checkerboard 8x8 matrix using the tile function
a = np.tile(([1,0],[0,1]),(4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### Q_NO_22

In [109]:
# Normalize a 5x5 random matrix
a = np.random.random((5,5))
b = (a - np.mean(a))/np.std(a)
b

array([[ 0.65128514, -0.81425149,  1.57792417, -0.88199431, -1.24935735],
       [ 1.38966953,  1.06912169,  1.01979723, -0.96423469,  1.21434272],
       [ 1.61813219, -1.11540689,  0.24034629, -0.52083175,  1.03511832],
       [-1.53182957,  1.25249094, -0.24997969, -0.88809115, -0.31195387],
       [-0.838696  , -0.54708079,  0.38486433, -0.54254796, -0.99683705]])

### Q_NO_23

In [112]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 
a = np.dtype([('r',np.ubyte),
               ('g',np.ubyte),
               ('b',np.ubyte),
               ('a',np.ubyte)])
a
              

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### Q_NO_24

In [123]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.ones((5,3))
print(a)
b = np.ones((3,2))
print(b)
c = np.dot(a,b)
c

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

### Q_NO_25

In [130]:
# Given a 1D array, negate all elements which are between 3 and 8, in place. 
a = np.arange(11)
a[(3<a) & (a <8)] *= -1
a
    

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

### Q_NO_26

In [131]:
# What is the output of the following script? 
# python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


### Q_NO_27

In [142]:
# Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z = np.arange(5)
print(Z**Z)

print(2 << Z >> 2)

print(Z <- Z)

print(1j*Z)

print(Z/1/1)

print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Q_NO_28

In [144]:
# What are the result of the following expressions? (★☆☆)

a = np.array(0) / np.array(0)
print(a)
b = np.array(0) // np.array(0)
print(b)
c = np.array([np.nan]).astype(int).astype(float)
print(c)

nan
0
[-9.22337204e+18]


/tmp/ipykernel_106/3273011606.py:3: RuntimeWarning: invalid value encountered in divide
  a = np.array(0) / np.array(0)
/tmp/ipykernel_106/3273011606.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  b = np.array(0) // np.array(0)
/tmp/ipykernel_106/3273011606.py:7: RuntimeWarning: invalid value encountered in cast
  c = np.array([np.nan]).astype(int).astype(float)


### Q_NO_29

In [162]:
# How to round away from zero a float array ? 
a = np.array((2.10,5.40), dtype = int)
a


array([2, 5])

In [163]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 7. -4.  7.  8.  2. -8. 10. -7. -5. -5.]


### Q_NO_30

In [169]:
# How to find common values between two arrays?
a = np.array([1,2,3,4,5,6,7,8])
print(a)
b = np.array([5,6,7,8,9,10,11,12])
print(b)
c = np.intersect1d(a,b)
c

[1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10 11 12]


array([5, 6, 7, 8])

### Q_NO_31

In [180]:
# How to ignore all numpy warnings (not recommended)? 
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
     np.arange(3) / 0

[inf]


### Q_NO_32

In [181]:
# Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)


/tmp/ipykernel_106/1519088985.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### Q_NO_33

In [193]:
#  How to get the dates of yesterday, today and tomorrow?
a = np.datetime64('today')
b = np.datetime64('today') - np.timedelta64(1)
c = np.datetime64('today') + np.timedelta64(1)
print(a)
print(b)
print(c)

2023-02-20
2023-02-19
2023-02-21


### Q_NO_34

In [201]:
#  How to get all the dates corresponding to the month of July 2016?
a = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

### Q_NO_35

In [209]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
a = np.ones(3)*1
b = np.ones(3)*2
print(a)
print(b)
np.add(a,b,out = b)
np.divide(a,2, out = a)
np.negative(a,out = a)
np.multiply(a,b, out = a)


[1. 1. 1.]
[2. 2. 2.]


array([-1.5, -1.5, -1.5])

### Q_NO_36

In [237]:
#  Extract the integer part of a random array of positive numbers using 4 different methods 
# a = np.array([1,3,4,5])
# b = np.array([3,4,5,6])
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7. 0. 4. 7. 6. 1. 7. 6. 5. 2.]
[7. 0. 4. 7. 6. 1. 7. 6. 5. 2.]
[7. 0. 4. 7. 6. 1. 7. 6. 5. 2.]
[7 0 4 7 6 1 7 6 5 2]
[7. 0. 4. 7. 6. 1. 7. 6. 5. 2.]


### Q_NO_37

In [247]:
# Create a 5x5 matrix with row values ranging from 0 to 4
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Q_NO_38

In [267]:
# Consider a generator function that generates 10 integers and use it to build an array 
def genrator():
    for x in range(10):
        yield x
a  = np.fromiter(genrator(), dtype = float, count = -1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Q_NO_39

In [270]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
a = np.linspace(1,0)
a

array([1.        , 0.97959184, 0.95918367, 0.93877551, 0.91836735,
       0.89795918, 0.87755102, 0.85714286, 0.83673469, 0.81632653,
       0.79591837, 0.7755102 , 0.75510204, 0.73469388, 0.71428571,
       0.69387755, 0.67346939, 0.65306122, 0.63265306, 0.6122449 ,
       0.59183673, 0.57142857, 0.55102041, 0.53061224, 0.51020408,
       0.48979592, 0.46938776, 0.44897959, 0.42857143, 0.40816327,
       0.3877551 , 0.36734694, 0.34693878, 0.32653061, 0.30612245,
       0.28571429, 0.26530612, 0.24489796, 0.2244898 , 0.20408163,
       0.18367347, 0.16326531, 0.14285714, 0.12244898, 0.10204082,
       0.08163265, 0.06122449, 0.04081633, 0.02040816, 0.        ])

In [271]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### Q_NO_40

In [275]:
# Create a random vector of size 10 and sort it 
a = np.random.random(10)
a.sort()
a

array([0.16567373, 0.20975208, 0.31235991, 0.37755515, 0.49841576,
       0.56227327, 0.72781606, 0.77326095, 0.80809176, 0.82242963])

### Q_NO_41

In [281]:
# How to sum a small array faster than np.sum?
a  =  np.arange(10)
b = np.add.reduce(a)
b

45

### Q_NO_42

In [289]:
# Consider two random array A and B, check if they are equal
a  = np.random.random(5)
print(a)
b = np.random.random(5)
print(b)
c = np.array_equal(a,b)
c

[0.8203559  0.82881113 0.35400526 0.07703186 0.44007464]
[0.03178413 0.52330537 0.39422178 0.831278   0.12929327]


False

In [295]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


### Q_NO_43

In [298]:
# Make an array immutable (read-only)
a = np.array([1,2,3,4])
a.flags.writeable = False
a[2] = 1
a

ValueError: assignment destination is read-only

### Q_NO_44

In [301]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.91657209 0.82424669 0.06720054 0.59058985 0.67166685 0.88025273
 0.86584608 0.67098926 0.55262264 0.86055603]
[0.95691249 0.07994092 1.31591573 0.63963099 0.12320158 0.24784511
 0.29506342 1.02974478 0.75278167 0.32529177]


### Q_NO_45

In [316]:
# Create random vector of size 10 and replace the maximum value by 0
# a = np.random.random(10)
# a[a.argmax() ] ==  0 
# a

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.19109218 0.38797224 0.48612833 0.         0.2117278  0.27242034
 0.22742121 0.26370845 0.32704408 0.14142065]


### Q_NO_46

In [317]:
# Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### Q_NO_47

In [318]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


### Q_NO_48

In [319]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### Q_NO_49

In [320]:
# How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Q_NO_50

In [321]:
# How to find the closest value (to a given scalar) in a vector? 
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

19


### Q_NO_51

In [3]:
#  Create a structured array representing a position (x,y) and a color (r,g,b)
import numpy as np
a = np.zeros(10,[ ('position', [ ('x', float, 1),
                                 ('y', float, 1)]),
                  ('color', [ ('r', float, 1),
                             ('g', float, 1),
                             ('b', float, 1)])])
                                
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_67/3902896178.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10,[ ('position', [ ('x', float, 1),


In [4]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_67/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


### Q_NO_52

In [8]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.72489553 0.48604721 0.61843011 0.82328153 0.44047911
  0.14836822 0.19202081 0.67484165 0.33694423]
 [0.72489553 0.         0.2755753  0.71621396 0.89209945 1.04846094
  0.62819293 0.86246449 0.32751539 0.39089533]
 [0.48604721 0.2755753  0.         0.69649547 0.90620087 0.87020497
  0.42643742 0.6512315  0.43534197 0.1588046 ]
 [0.61843011 0.71621396 0.69649547 0.         0.218811   0.57095734
  0.48074207 0.57084752 0.41495623 0.59115911]
 [0.82328153 0.89209945 0.90620087 0.218811   0.         0.6862785
  0.69209208 0.74812186 0.56948617 0.80827069]
 [0.44047911 1.04846094 0.87020497 0.57095734 0.6862785  0.
  0.44423249 0.24937023 0.86599612 0.71157958]
 [0.14836822 0.62819293 0.42643742 0.48074207 0.69209208 0.44423249
  0.         0.23427992 0.53565653 0.26764449]
 [0.19202081 0.86246449 0.6512315  0.57084752 0.74812186 0.24937023
  0.23427992 0.         0.74477229 0.49382905]
 [0.67484165 0.32751539 0.43534197 0.41495623 0.56948617 0.86599612
  0.53565653 0.744772

### Q_NO_53

In [88]:
#  How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:,:] = Z
print(Y)

[ 4 86 15 43 75 12 52 21 27 64]


### Q_NO_54

In [ ]:
# How to read the following file? 

# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11


In [21]:
import numpy as np
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


### Q_NO_55

In [ ]:
# What is the equivalent of enumerate for numpy arrays?
a = np.

In [35]:
a = np.array([1,2,3,4,5])
b= np.array([[11,22,33,4,5],[6,6,6,6,6],[5,5,5,5,5]])


array([6, 6, 6, 6, 6])

In [39]:
a = np.empty(1)
a

array([6.95330279e-310])

In [40]:
a = np.arange(3,20,3)
a

array([ 3,  6,  9, 12, 15, 18])

In [48]:
a = np.linspace(2,20, num = 5, dtype=np.int64)
a

array([ 2,  6, 11, 15, 20])

In [65]:
a = np.array([[1,3,2,4],[2,3,4,5]])
b = np.array([[4,3,2,1]])

c = np.concatenate((a,b), axis = 0)
c

array([[1, 3, 2, 4],
       [2, 3, 4, 5],
       [4, 3, 2, 1]])

In [76]:
a  = np.array([[[1,2,3,4,5]],
              [[3,4,5,6,7]],
              [[4,5,6,7,8]]])
a.ndim

3

In [77]:
a.size

15

In [78]:
a.shape

(3, 1, 5)

In [87]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a[np.newaxis, :]
b.shape

(1, 9)

In [86]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape

(9,)

### Q

In [217]:
# Non zero values

In [219]:
a = np.array([1,0,9,0,8,7,0])
c = np.nonzero(a)
c
# provide indexing of non zero values of givenn list

(array([0, 2, 4, 5]),)