### Lecture 21:   if, if else,if elif else, nested if

### if statemnt:
The IF statement is a decision-making statement that guides a program to make decisions based on specified criteria. The IF statement executes one set of code if a specified condition is met (TRUE) or another set of code evaluates to FALSE.

In [6]:
if True:
   print("i am right")

i am right


In [8]:
if False:
    print("i am right")


In [9]:
if False:
    print("i am right")
print('bye')

bye


In [29]:
x = 9
r = x % 2
if r == 0:
    print('even')
if (r == 1):
    
    print('odd')
print('bye')

odd
bye


In [38]:
x = 6
r = x % 2
if r == 0:
    print('even')
    if x > 4: 
        print('Great')
else:
    
    print('odd')
print('bye')

even
Great
bye


### if else
An if else Python statement evaluates whether an expression is true or false. If a condition is true, the “if” statement executes. Otherwise, the “else” statement executes. Python if else statements help coders control the flow of their programs.

In [64]:
x = 8
r = x % 2
if r == 0:
    print('even')
    if x > 4: 
        print('Great')
    else:
        ('not to great')
else:
    
    print('odd')
print('bye')

even
Great
bye


In [48]:
x = 3
r = x % 2
if r == 0:
    print('even')
    if x > 3: 
        print('Great')
    else:
        ('not to great')
else:
    
    print('odd')
print('bye')

odd
bye


In [55]:
x = 4;
if x == 1:
    print('one')
if x == 2:
    print('two')
if x == 3:
    print('three')
if x == 4:
    print('four')

four


### elif
The elif is short for else if. It allows us to check for multiple expressions. If the condition for if is False , it checks the condition of the next elif block and so on. If all the conditions are False , the body of else is executed.

In [66]:
x = 2;
if x == 1:
    print('one')
elif x == 2:
    print('two')
elif x == 3:
    print('three')
elif x == 4:
    print('four')

two


In [67]:
x = 5;
if x == 1:
    print('one')
elif x == 2:
    print('two')
elif x == 3:
    print('three')
elif x == 4:
    print('four')
else:
    print('out of range')

out of range


### Lecture 22: while loop, Nested while loop

### while loop
Python While Loop is used to execute a block of statements repeatedly until a given condition is satisfied. And when the condition becomes false, the line immediately after the loop in the program is executed. While loop falls under the category of indefinite iteration

In [16]:
g = 6
while g<=10:
        print("Rizwan")
        g = g + 1

Rizwan
Rizwan
Rizwan
Rizwan
Rizwan


##### we keep in mind while useing of while loop
(1) initalization (2) condition  (3)  increment/Decrement

In [19]:
g = 5 
while g>=1:
        print("Rizwan")
        g = g - 1

Rizwan
Rizwan
Rizwan
Rizwan
Rizwan


In [21]:
g = 5
while g>=1:
        print("Rizwan",g)
        g = g - 1

Rizwan 5
Rizwan 4
Rizwan 3
Rizwan 2
Rizwan 1


In [22]:
g = 10
while g>=3:
        print("Rizwan",g)
        g = g - 1

Rizwan 10
Rizwan 9
Rizwan 8
Rizwan 7
Rizwan 6
Rizwan 5
Rizwan 4
Rizwan 3


### Nested while loop
When a while loop is present inside another while loop then it is called nested while loop. Lets take an example to understand this concept. i = 1 j = 5 while i < 4: while j < 8: print(i, ",", j) j = j + 1 i = i + 1.

#using while loop inside while loop called nested loop.

In [13]:
g = 5
h = 1
while g>=1:
        h = 1
        print("Rizwan", end = " ")
        while h <= 5:
            print('rocks',end = " ")
            h = h+1
        g = g - 1
        print()

Rizwan rocks rocks rocks rocks rocks 
Rizwan rocks rocks rocks rocks rocks 
Rizwan rocks rocks rocks rocks rocks 
Rizwan rocks rocks rocks rocks rocks 
Rizwan rocks rocks rocks rocks rocks 


In [1]:
g = 5
h = 1
while g>=1:
        h = 1
        print("#", end = " ")
        while h <= 5:
            print('#',end = " ")
            h = h+1
        g = g  - 1
        print()

# # # # # # 
# # # # # # 
# # # # # # 
# # # # # # 
# # # # # # 


### For LOOP
In the context of most data science work, Python for loops are used to loop through an iterable object (like a list, tuple, set, etc.) and perform the same action for each entry. For example, a for loop would allow us to iterate through a list, performing the same action on each item in the list.

In [3]:
x = ['rizwan',24,3.4]

In [4]:
for i in x:
    print(i)

rizwan
24
3.4


In [8]:
x = 'MAYO'
for i in x:
    print(i)

M
A
Y
O


In [11]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [12]:
for i in range(20,50,5):
    print(i)

20
25
30
35
40
45


In [16]:
for r in range(20,5,-3):
    print(r)

20
17
14
11
8


In [25]:
for i in range(10):
    if i != 2:
        print(i)
    

0
1
3
4
5
6
7
8
9


### Break, continue, pass, key words in python
The main difference between break and continue statement is that when break keyword is encountered, it will exit the loop. Python Pass Statement is used as a placeholder inside loops, functions, class, if-statement that is meant to be implemented later.

In [5]:
av = 10
x = int(input("How many candes you want:"))
i =1
while i <= x:
    if i > av:
        break
    print('Candy')
    i+= 1

How many candes you want:5
Candy
Candy
Candy
Candy
Candy


In [2]:
av = 5
x = int(input("How many candes you want:"))
i =1
while i <= x:
    if i > av:
        break
    print('Candy')
    i+= 1
    
print("BYE")

How many candes you want:6
Candy
Candy
Candy
Candy
Candy
BYE


In [5]:
av = 5
x = int(input("How many candes you want:"))
i =1
while i <= x:
    if i > av:
        print('out of stoke')
        break
    print('Candy')
    i+= 1

How many candes you want:6
Candy
Candy
Candy
Candy
Candy
out of stoke


In [14]:
for i in range(1,101):
    if i % 3 == 0 or i % 5 == 0 :
        continue
    print(i)

print("bye")

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
52
53
56
58
59
61
62
64
67
68
71
73
74
76
77
79
82
83
86
88
89
91
92
94
97
98
bye


In [15]:
for i in range(1,101):
    if i % 3 == 0 and i % 5 == 0 :
        continue
    print(i)

print("bye")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
16
17
18
19
20
21
22
23
24
25
26
27
28
29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
47
48
49
50
51
52
53
54
55
56
57
58
59
61
62
63
64
65
66
67
68
69
70
71
72
73
74
76
77
78
79
80
81
82
83
84
85
86
87
88
89
91
92
93
94
95
96
97
98
99
100
bye


In [29]:
for i in range(1,101):
    if i % 2 != 0:
        pass
    else:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


### Lecture 22.1: Break vs continue vs pass
The Python break statement stops the loop in which the statement is placed. A Python continue statement skips a single iteration in a loop. Both break and continue statements can be used in a for or a while loop. ... The continue statement allows you to skip part of a loop when a condition is met

In [33]:
for i in range (5):
    if i == 2:
        continue
    
    print("Hello",i)

Hello 0
Hello 1
Hello 3
Hello 4


In [34]:
for i in range (5):
    if i == 3:
        break
    
    print("Hello",i)

Hello 0
Hello 1
Hello 2


In [38]:
def fun():
    print("hello")
    print("hello")
    print("hello")

In [39]:
def fun():
    pass
a = 5

In [40]:
class human:
    pass

### Lecture 23: Printing patterns in python.

In [45]:
for i in range(5):
    for j in range(8):
        print("@",end = "")
        
    print()

@@@@@@@@
@@@@@@@@
@@@@@@@@
@@@@@@@@
@@@@@@@@


In [56]:
for i in range(4):
    for j in range(i + 1):
        print("#",end = "")
        
    print()

#
##
###
####


In [62]:
for i in range(5):
    for j in range(5 - i):
        print("#",end = "")
        
    print()

#####
####
###
##
#


### Lecture 24: For else in python
Python allows the else keyword to be used with the for and while loops too. The else block appears after the body of the loop. The statements in the else block will be executed after all iterations are completed. The program exits the loop only after the else block is executed.

In [68]:
numbers = [12,25,20,15,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)

25
20
15


In [69]:
numbers = [12,25,20,15,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)
        break

25


In [70]:
numbers = [12,26,19,16,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)
        break

In [76]:
numbers = [12,26,19,16,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)
        break
    else:
        print("not found")

not found
not found
not found
not found
not found
not found


In [77]:
numbers = [12,26,19,16,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)
        break
else:
        print("not found")

not found


In [80]:
numbers = [10,26,19,16,43,34]
for num in numbers:
    if num % 5 == 0:
        print(num)
        break
    else:
        print("not found")

10


### Lecture 25: Prime Numbers
2, 3, 5, 7 etc. are prime numbers as they do not have any other factors. But 6 is not prime (it is composite) since, 2 x 3 = 6 
#Write a code for checking that a given number is prime number or not.

In [87]:
num = 7
for i in range(2,num):
    if num % i == 0:
        print("Not prime")
        break
else:
    print("prime")



prime


In [88]:
num = 10
for i in range(2,num):
    if num % i == 0:
        print("Not prime")
        break
else:
    print("prime")


Not prime


### Lecture 26: Array in Python
Python arrays are a data structure like lists. They contain a number of objects that can be of different data types. ... For example, if you have a list of student names that you want to store, you may want to store them in an array. Arrays are useful if you want to work with many values of the same Python data type.

In [100]:
from array import *
values = ('i',[2,3,4,5])
print(values)

('i', [2, 3, 4, 5])


In [115]:

values =array ('i',[2,-37,4,5])
print(values)

array('i', [2, -37, 4, 5])


In [119]:

values =array('i',[2,-37,4,5])
values.reverse()
print(values)


array('i', [5, 4, -37, 2])


In [120]:
values =array('i',[2,-37,4,5])
print(values[0])


2


In [124]:
values =array('i',[2,-37,4,5])

print(values[3])


5


In [3]:
from array import *
val = array('i',[2,-37,4,5])
for e in val:
    print(e)


2
-37
4
5


In [6]:
from array import *
v = array('u',[e,a,i])
for e in v:
    print(e)



NameError: name 'a' is not defined

### Lecture 27: Array values fron user in python.
In Python, we can get user input like this: name = input("Enter your name: ") print("Hello", name + "!") The code above simply prompts the user for information, and the prints out what they entered in

In [1]:
from array import *

arr = array('i',[])

n = int(input("Enter the length of value of array "))

for i in range(5):
    x = int(input("enter the value "))
    arr.append(x)
    
print(x)


Enter the length of value of array 5
enter the value 6
enter the value 8
enter the value 3
enter the value 6
enter the value 2
2


In [9]:
 from array import *

arr = array('i',[])

n = int(input("Enter the length of value of array"))

for i in range(n):
    x = int(input("enter the value"))
    arr.append(x)
    
print(arr)

Enter the length of value of array5
enter the value7
enter the value6
enter the value5
enter the value4
enter the value3
array('i', [7, 6, 5, 4, 3])


In [13]:
from array import *

arr = array('i',[])

n = int(input("Enter the length of value of array"))

for i in range(5):
    x = int(input("enter the value"))
    arr.append(x)
    
print(arr)

val = int(input("Enter the value for search"))

k = 0
for e in arr:
    if e == val:
        print(k)
        break
    k  += 1

Enter the length of value of array5
enter the value6
enter the value7
enter the value8
enter the value9
enter the value3
array('i', [6, 7, 8, 9, 3])
Enter the value for search9
3


In [14]:
from array import *

arr = array('i',[])

n = int(input("Enter the length of value of array"))

for i in range(5):
    x = int(input("enter the value"))
    arr.append(x)
    
print(arr)

val = int(input("Enter the value for search"))

k = 0
for e in arr:
    if e == val:
        print(k)
        break
    k  += 1
print(arr.index(val))

Enter the length of value of array6
enter the value55
enter the value44
enter the value33
enter the value22
enter the value11
array('i', [55, 44, 33, 22, 11])
Enter the value for search33
2
2


##### in the above code 2,2 comes. in this first 2 because of
above code and second 2 comes bc of last line code.

### Lecture 28: Numpy,numpy arrys
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [4]:
from numpy import *

In [9]:
arr = array([1,2,3,4,5,6],int)

In [10]:
print(arr)

[1 2 3 4 5 6]


In [12]:
arr = array([1,2,3,4,5,6],char)

TypeError: Cannot interpret '<module 'numpy.core.defchararray' from 'd:\\Users\\M.Rizwan\\anaconda3\\lib\\site-packages\\numpy\\core\\defchararray.py'>' as a data type

In [13]:
print(arr)

[1 2 3 4 5 6]


### Lecture 29: Diffrent ways of creating arrays in numpay.
Array in Python can be created by importing array module. array(data_type, value_list) is used to create an array with data type and value list specified in its arguments.

In [15]:
#  6 ways to create arrays in python 

### 1) Array()
An array is a collection of elements of the same type placed in contiguous memory locations that can be individually referenced by using an index to a unique identifier. Five values of type int can be declared as an array without having to declare five different variables (each with its own identifier)

In [17]:
from numpy import*

In [18]:
arr = array([1,2,3,4,5])

In [19]:
print(arr)

[1 2 3 4 5]


In [20]:
arr = array([1,2,3,4,5])

In [23]:
print(arr.dtype)

int32


In [25]:
arr = array([1,2,3,4,5.5])

In [28]:
print(arr.dtype)
print(arr)

float64
[1.  2.  3.  4.  5.5]


In [30]:
arr = array([1,2,3,4,5.5],int)

In [31]:
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5]


In [33]:
arr = array([1,2,3,4,55],float)

In [34]:
print(arr.dtype)
print(arr)

float64
[ 1.  2.  3.  4. 55.]


### 2): linspace()
What does Linspace do in Python?
Image result for linspace in python
linspace) is a tool in Python for creating numeric sequences. It's somewhat similar to the NumPy arange function, in that it creates sequences of evenly spaced numbers structured as a NumPy array.

In [36]:
arr = linspace(1,10,11)

In [37]:
print(arr)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [38]:
arr = linspace(1,10,9)

In [39]:
print(arr)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [40]:
arr = linspace(1,10,10)

In [41]:
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [42]:
arr = linspace(1,10,20)

In [43]:
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [44]:
arr = linspace(1,10)

In [45]:
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


### 3) Arrange
arrange() It creates an array by using the evenly spaced values over the given interval. The interval mentioned is half opened i.e. [Start, Stop]).

In [48]:
 arr = arange(1,20,4)

In [49]:
print(arr)

[ 1  5  9 13 17]


### 4) logspace
logspace() in Python. The numpy. logspace() function returns number spaces evenly w.r.t interval on a log scale.

In [51]:
arr = logspace(1,20,3)

In [52]:
print(arr)

[1.00000000e+01 3.16227766e+10 1.00000000e+20]


In [53]:
arr = logspace(1,20,6)

In [54]:
print(arr)

[1.00000000e+01 6.30957344e+04 3.98107171e+08 2.51188643e+12
 1.58489319e+16 1.00000000e+20]


In [57]:
arr = logspace(1,20,3)

In [59]:
print('%.2f' %arr[0])

10.00


In [60]:
arr = logspace(1,20,3)

In [61]:
print('%.2f' %arr[1])

31622776601.68


In [62]:
print('%.2f' %arr[2])

100000000000000000000.00


### 5) zeros()
The zeros() function is used to get a new array of given shape and type, filled with zeros. Shape of the new array, e.g., (2, 3) or 2. The desired data-type for the array, e.g., numpy. int8

In [64]:
arr = zeros(5)

In [65]:
print(arr)

[0. 0. 0. 0. 0.]


### 6) ones()
ones() function returns a new array of given shape and data type, where the element's value is set to 1. This function is very similar to numpy zeros() function.

In [72]:
arr = ones(4)

In [73]:
print(arr)

[1. 1. 1. 1.]


In [76]:
arr = ones(4,int)

In [77]:
print(arr)

[1 1 1 1]


### Lecture 30: coping an array in python
We can create a copy of an array by using the assignment operator (=). In Python, Assignment statements do not copy objects, they create bindings between a target and an object. When we use = operator user thinks that this creates a new object; well, it doesn't.

In [92]:
from numpy import *

In [93]:
arr = array([1,2,3,4,5])

In [94]:
arr

array([1, 2, 3, 4, 5])

In [95]:
arr + 4

array([5, 6, 7, 8, 9])

In [96]:
arr + 10

array([11, 12, 13, 14, 15])

In [97]:
arr1 = array([1,2,3,4,5])

In [98]:
arr2 = array([6,7,8,9,10])

In [99]:
arr = arr1 + arr2,#also called vectorized opration.

In [100]:
print(arr)

(array([ 7,  9, 11, 13, 15]),)


In [101]:
arr = array([1,2,3,4,5])

In [104]:
print(sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [105]:
print(cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [106]:
print(log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [107]:
arr

array([1, 2, 3, 4, 5])

In [108]:
print(sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [109]:
print(sum(arr))

15


In [110]:
print(min(arr))

1


In [111]:
print(max(arr))

5


In [112]:
arr1

array([1, 2, 3, 4, 5])

In [113]:
arr2

array([ 6,  7,  8,  9, 10])

In [117]:
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  6  7  8  9 10]


In [125]:
arr3 = ([2,4,6,8,10])

In [126]:
arr4 = ([1,3,5,7,9])

In [127]:
arr4

[1, 3, 5, 7, 9]

In [128]:
arr3

[2, 4, 6, 8, 10]

In [129]:
arr3 = arr4

In [131]:
print(arr4)
print(arr3)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


In [133]:
print(id(arr4))
print(id(arr3))


2725507737984
2725507737984


##### this also called alising
In Python, aliasing happens whenever one variable's value is assigned to another variable, because variables are just names that store references to values.

In [152]:
arr5 = array([6,5,4,3])

In [153]:
arr7 = arr5.view()


In [156]:
arr5[1] = 7

In [157]:
print(arr5)
print(arr7)
print(id(arr5))
print(id(arr7))

[6 7 4 3]
[6 7 4 3]
2725507708272
2725507707888


### Two types of copy 
 1): shallow copy: changes both values and adress (e.g: view())
 2): Deep copy:chandes one value but both adress  (e.g: copy())
  simple copy:    arr1 = arr2 (alising)
    

##### 1): shallow copy: 
A shallow copy means constructing a new collection object and then populating it with references to the child objects found in the original. The copying process does not recurse and therefore won't create copies of the child objects themselves. In case of shallow copy, a reference of object is copied in other object.

### 2): Deep copy:
Deep copy is a process in which the copying process occurs recursively. It means first constructing a new collection object and then recursively populating it with copies of the child objects found in the original. In case of deep copy, a copy of object is copied in other object.

In [161]:
arr5 = array([6,5,4,3])

In [162]:
arr7 = arr5.copy()

In [163]:
arr5[1] = 7

In [164]:
print(arr5)
print(arr7)
print(id(arr5))
print(id(arr7))

[6 7 4 3]
[6 5 4 3]
2725507917936
2725507918608


In [165]:
#END