### Lecture 31: Working with matrix in python
Matrix is one of the important data structures that can be used in mathematical and scientific calculations. Python does not have a straightforward way to implement a matrix data type. Python matrix can be created using a nested list data type and by using the numpy library

In [3]:
from numpy import *

In [8]:
arr1 = array([
                [1,2,3,4,5],
    
                [6,7,8,9,0]
])

In [9]:
print(arr1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [10]:
print(arr1.dtype)

int32


In [11]:
print(arr1.ndim)

2


In [12]:
print(arr1.shape)

(2, 5)


In [13]:
print(arr1.size)

10


In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [15]:
arr2 = arr1.flatten()

In [16]:
print(arr2)

[1 2 3 4 5 6 7 8 9 0]


In [17]:
arr3 = array([
                [1,2,3,4,5,7,5,4],
    
                [6,7,8,9,0,5,6,7]
])

In [18]:
print(arr3.ndim)

2


In [19]:
arr4 = arr3.flatten()

In [20]:
print(arr4)

[1 2 3 4 5 7 5 4 6 7 8 9 0 5 6 7]


In [21]:
print(arr4.ndim)

1


In [22]:
arr5 = arr4.reshape(4,4)

In [23]:
print(arr5)

[[1 2 3 4]
 [5 7 5 4]
 [6 7 8 9]
 [0 5 6 7]]


In [26]:
arr5 = arr4.reshape(2,4,2)

In [27]:
print(arr5)

[[[1 2]
  [3 4]
  [5 7]
  [5 4]]

 [[6 7]
  [8 9]
  [0 5]
  [6 7]]]


In [29]:
arr5 = arr4.reshape(2,2,4)

In [30]:
print(arr5)

[[[1 2 3 4]
  [5 7 5 4]]

 [[6 7 8 9]
  [0 5 6 7]]]


In [31]:
print(arr5.ndim)

3


In [32]:
arr1 = array([
                [1,2,3,4,5],
    
                [6,7,8,9,0]
])

In [33]:
print(arr1)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [34]:
m = matrix(arr1)

In [35]:
print(m)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [40]:
m = matrix('4 5 6 7 ; 5 6 7 8')

In [41]:
print(m)

[[4 5 6 7]
 [5 6 7 8]]


In [42]:
m = matrix('4 5; 6 7 ; 5 6; 7 8')

In [43]:
print(m)

[[4 5]
 [6 7]
 [5 6]
 [7 8]]


In [52]:
m = matrix('4 5 6 ;7 8 6; 7 8,9')

In [53]:
print(m)

[[4 5 6]
 [7 8 6]
 [7 8 9]]


In [54]:
m

matrix([[4, 5, 6],
        [7, 8, 6],
        [7, 8, 9]])

In [55]:
print(diagonal(m))

[4 8 9]


In [56]:
print(m.min())

4


In [57]:
print(m.max())

9


In [59]:
m1 = matrix('1 2 3;4 5 6;7 8 9')

In [60]:
m2 = matrix('9 8 7;6 5 4;3 2 1')

In [63]:
m3 = m1 + m2

In [64]:
print(m3)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [65]:
m3 = m1 * m2

In [66]:
print(m3)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Lecture 32: FUNCTIONS IN PYTHON.
A function is a block of code that only runs when it is called. Python functions return a value using a return statement, if one is specified. A function can be called anywhere after the function has been declared. By itself, a function does nothing.

#### Types of Functions in Python
Python Function with no argument and no return value.
Function with no argument and with a Return value.
Python Function with argument and No Return value.
Function with argument and return value.

In [4]:
def fun():
    print("M.Rizwan")
    print(" Akram")

In [6]:
fun()

M.Rizwan
 Akram


In [8]:
def add(x,y):
    c = x + y
    print(c)


In [9]:
add(5,5)

10


In [10]:
add(50,50)

100


In [11]:
add(1000,1000)

2000


In [12]:
def sub(x,y):
    c = x - y
    print(c)

In [13]:
sub(10,7)

3


In [14]:
sub(100000,45465)

54535


In [17]:
sub(4,6)

-2


In [18]:
def add(x,y,z):
    c = x + y +z
    print(c)

In [19]:
add(2,3,4)

9


In [20]:
add(45,78,90)

213


In [23]:
add(3,678567,345644)

1024214


In [24]:
def sub(x,y,z):
    c = x - y - z
    print(c)

In [25]:
sub(5,4,3)

-2


In [26]:
sub(434,32,21)

381


In [27]:
def mul(x,y):
    c = x *y
    print(c)

In [28]:
mul(3,4)

12


In [29]:
mul(6,6)

36


In [30]:
mul(34,789)

26826


In [31]:
def mul(x,y,z):
    c = x * y * z
    print(c)

In [32]:
mul(2,2,2)

8


In [33]:
mul(12,3,1)

36


In [34]:
mul(456,786,433)

155194128


In [38]:
def add(x,y):
    c = x + y
    return c
mul(2,3,4)
result = add(4,5)
print(result)

24
9


In [40]:
def add(x,y,z):
    c = x + y + z
    return c
sub(6,7,8)
result = add(6,7,8)
print(result)
    

-9
21


In [44]:
def add_sub(x,y):
    a = x + y
    b = x - y
    return a,b
result1, result2 = add_sub(5,5)
print(result1,result2)

10 0


In [ ]:
#end

### Lecture 33: Function arguments.
The terms parameter and argument can be used for the same thing: information that are passed into a function. From a function's perspective: A parameter is the variable listed inside the parentheses in the function definition. An argument is the value that are sent to the function when it is called.

### Mutable and immutable arguments.
Objects of built-in types like int , float , bool , str , tuple , and Unicode are immutable. Objects of built-in types like list , set , and dict are mutable. A mutable object can change its state or contents, whereas immutable objects cannot.



In [2]:
def update(x):
    print(id(x))
    x = 9
    print(id(x))
    print("x = ",x)

In [11]:
a  = 5
print(id(a))
update(a)
print('a = ',a)

140735748843440
140735748843440
140735748843568
x =  9
a =  5


In [17]:
def update(list):
    print(id(list))
    list [1] = 9
    print(id(list))
    print("x = ",list)

In [18]:
list  = [34,66,77]
print(id(list))
update(list)
print('list= ',list)

2104344604096
2104344604096
2104344604096
x =  [34, 9, 77]
list=  [34, 9, 77]


In [19]:
#end

### Lecture 34: Types of arguments
5 Types of Arguments in Python Function Definition:
default arguments.
keyword arguments.
positional arguments.
arbitrary positional arguments.
arbitrary keyword arguments


##### Position:
The first positional argument always needs to be listed first when the function is called. The second positional argument needs to be listed second and the third positional argument listed third, etc. An example of positional arguments can be seen in Python's complex() function.


#### Keyword: 
Keyword arguments (or named arguments) are values that, when passed into a function, are identifiable by specific parameter names. A keyword argument is preceded by a parameter and the assignment operator, = . Keyword arguments can be likened to dictionaries in that they map a value to a keyword.

#### Default:
Python has a different way of representing syntax and default values for function arguments. Default values indicate that the function argument will take that value if no argument value is passed during the function call. The default value is assigned by using the assignment(=) operator of the form keywordname=value.

### Variable length:
You may need to process a function for more arguments than you specified while defining the function. These arguments are called variable-length arguments and are not named in the function definition, unlike required and default arguments.

In [21]:
def add(x,y):                        # x and y called formal arguments
    a = x + y
    print(a)

In [24]:
add(4,3)                             #4 and 3 called actual arguments.
                                    #Actal arguments have four types.
                                    #position,keyword,default,variable length

7


In [28]:
def person(name,age):
    print(name)
    print(age)

In [29]:
person('ali',20)

ali
20


In [32]:
def person(name,age):
    print(name)
    print(age)

In [33]:
person(20,"Ali")

20
Ali


In [35]:
person(age = 20,name = "Ali")                      #keyword argument

Ali
20


In [38]:
def person(name,age = 18):                       #defult argument
    print(name)
    print(age)

In [39]:
person("Ali")

Ali
18


In [40]:
person(50,"Ali")                       #override

50
Ali


In [41]:
def sum(a,b):
    c = a + b
    print(c)

In [42]:
sum(4,5)

9


In [48]:
def sum(a, * b):                        # variable length argument
                                    #  *  use for multipate values
    #c = a + b
    print(a)
    print(b)

In [49]:
sum(3,5,6,7)

3
(5, 6, 7)


In [62]:
def sum(a,*b):
    c = a 
     
    for i in b:
        c = c + i
    
    print(c)

In [63]:
sum(2,30,10,20)

62


In [66]:
def sum(*b):
    c = 0

     
    for i in b:
        c = c + i
    
    print(c)

In [67]:
sum(3,4,5,6)

18


In [68]:
# end

### Lecture 35: Keyworded Variable Length Arguments in Python | **kwargs

The special syntax *args in function definitions in python is used to pass a variable number of arguments to a function. It is used to pass a non-key worded, variable-length argument list. The syntax is to use the symbol * to take in a variable number of arguments; by convention, it is often used with the word args

In [75]:
def person(name, *data):
    print(name)
    print(data)

In [76]:
person('Rizwan',22,'Lahore',3098581002)

Rizwan
(22, 'Lahore', 3098581002)


In [82]:
def person(name, **data):             # ** mean passing multipale arguments but
                                      #  with the help of keywords
    print(name)
    print(data)

In [84]:
person('Rizwan',age = 22,city = 'Lahore',no = 3098581002)

Rizwan
{'age': 22, 'city': 'Lahore', 'no': 3098581002}


In [93]:
def person(name, **data):
    print(name)
    
    for i,j in data.items():
        print(i,j)
    

In [94]:
person('Rizwan',age = 22,city = 'Lahore',no = 3098581002)

Rizwan
age 22
city Lahore
no 3098581002


In [95]:
#end 

### 36: Global Keyword in Python | Global vs Local Variable
Global variables are variables declared outside a function. Local variables are variables declared inside a function. While global variables cannot be directly changed in a function, you can use the global keyword to create a function that will change the value of a global variable.

In [104]:

a = 10                #Globle variable = scope of this fun is everywhere.
def something():      #local variable = we cannot use this fun outside.
    a = 15
    b = 9
    print("in function", a)
something() 
    
    
#print(b)


in function 15


In [105]:
print("out function", a)

out function 10


In [106]:
a = 10                
def something():      

    print("in function", a)
something() 
print("out function", a)

in function 10
out function 10


In [112]:
a = 10                
def something():
    global a
    a = 15      #  =?  ; want to change variable globaly
    print("in function", a)
something() 
print("out function", a)

in function 15
out function 15


In [118]:
a = 10  
print(id(a))
def something():
    a = 9
    x = globals()['a']
    
    print(id(x))
    print("in function", a)
something()
print("out function", a)

140735748843600
140735748843600
in function 9
out function 10


In [119]:
a = 10  
print(id(a))
def something():
    a = 9
    x = globals()['a']
    
    print(id(x))
    print("in function", a)
    globals()['a'] = 15
    
something()
print("out function", a)

140735748843600
140735748843600
in function 9
out function 15


In [120]:
# end

### Lecture 37: Pass a list to a function
In Python, you can unpack list , tuple , dict (dictionary) and pass its elements to function as arguments by adding * to list or tuple and ** to dictionary when calling function. Note that if list , tuple , or dict is specified as an argument without * or ** , it is not be unpacked and passed to the function as is.

In [126]:
def count(list):
    even = 0
    odd = 0
    for i in list:
        if i % 2 == 0:
            even += 1
        else:
            odd +=1
            
    return even,odd
    
list = [2,3,4,5,6,7,89,98,90,11,45,44,33]
even,odd = count(list)

print("even : {} and odd : {}".format(even,odd))

even : 6 and odd : 7


In [127]:
# end

### 38:Fibonacci sequence in python.
Fibonacci numbers are a sequence of whole numbers: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ... This infinite sequence is called the Fibonacci sequence.
0,1,1,2,3,5,8,13,21,34,.......

In [135]:
def fib(n):
    
    a = 0
    b = 1
    print(a)
    print(b)
    
    for i in range(2,n):
        c = a + b
        a = b
        b = c
        
        print(c)
fib(5)

0
1
1
2
3


In [138]:
def fib(n):
    
    a = 0
    b = 1
    if n == 1:
        print(a)
    else:
        print(a)
        print(b)
    
    for i in range(2,n):
        c = a + b
        a = b
        b = c
        
        print(c)
fib(1)

0


In [139]:
fib(5)

0
1
1
2
3


In [140]:
fib(10)

0
1
1
2
3
5
8
13
21
34


In [141]:
fib(-3) # assigment = ?., how to corret this erroe?

0
1


In [142]:
fib(100)  # assig = how we get numbers till 89?

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
754011380474634642

In [143]:
def num(n):
    a=0
    b=1
    if(n<0):
        print("number is invalid")
    elif(n==1):
        print(a)
    else:
        print(0)
        print(1)
        c=0
        for i in range(2,n):
            c = a + b
            if(c<100):
                a=b
                b=c
                print(c)

num(100)

0
1
1
2
3
5
8
13
21
34
55
89


In [144]:
#end

### Lecture 39: Factorial of a Number
The Python factorial function factorial(n) is defined for a whole number n . This computes the product of all terms from n to 1 . factorial(0) is taken to be 1 . Therefore, factorial(4) = 4 * 3 * 2 * 1 = 24.

In [157]:
def fact(n):
    f = 1
    for i in range(1,n+1):
        f = f * i
    return f
    
    
x = 4
result = fact(x)
print(result)

24


[2 3 4 5]


In [158]:
#end

### Lecture 40: Recurrion:
Python also accepts function recursion, which means a defined function can call itself. Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.

#calling a function from itself

In [166]:
import sys
print(sys.getrecursionlimit())


def greet():
    print("hello")
    greet()


3000


In [169]:
import sys
sys.setrecursionlimit(10000)
print(sys.getrecursionlimit())


def greet():
    print("hello")
    greet()

10000


In [1]:
import sys
sys.setrecursionlimit(10000)
print(sys.getrecursionlimit())
i = 0

def greet():
    global i
    i+=1
    print("hello",1)
    
greet()

10000
hello 1


In [2]:
#  ?  upper cell

In [3]:
#end